version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: places_scraper_api
    container_name: places_scraper_api
    environment:
      - API_DEBUG=False
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    restart: on-failure
